- python/lsst/pex/config/rangeField.py
- tests/config.py
RangeField tried to swap min, max values if min > max
but the attempt used an invalid technique.
I removed that attempt and raise ValueError if min > max,
with equality allowed if both ends are inclusive.
I updated tests/config.py to check this new behavior
and also to test RangeField's checking of default values.
> DM-3638 Fix RangeField's handling of min > max

- python/lsst/pex/config/config.py
Conflicts:
python/lsst/pex/config/config.py
This is essentially a cherry-pick of HSC-1106's:
https://github.com/HyperSuprime-Cam/pex_config/commit/6e44b4e38cf53c743c550fefeba375652945ec69
> write config to tempfile and rename to avoid race.

- python/lsst/pex/config/config.py
cast future "newstr" objects to native "str" for consistency.
> Ensure that config uses native str internally

- python/lsst/pex/config/choiceField.py
- tests/ticketDM-7337.py
In Python 2 future "str" is not the same type as a string
literal such that the instance check fails. Overcome this by
converting a future "str" dtype to an __builtins__.str.
This may cause problems with unicode strings and may need to
be revisited to be a bit cleverer. Additionally there is
no handling of the case where a future str dtype is used and
the allowed strings are also future str.
> Handle ChoiceField dtype being a future str

- include/lsst/pex/config/pybind11.h
The pybind11 macros cover both versions of control field macros. They've been placed in a file that should hopefully disambiguate them from pybind11 utility code associated with other stack packages.
> DM-8363: Add macro for Pybind11 wrapping of LSST_CONTROL_FIELD

- python/lsst/pex/config/configDictField.py
- tests/configDictField.py
- tests/dictField.py
Make `ConfigDict.__setitem__` call `_autocast` before checking the key type, just like `Dict` does. Add a unicode key in the unit test for each so that this is tested (and I confirmed the fix by commenting out the call to `_autocast` in both dict classes, and two tests failed.
This solves a problem that pybind11 returns unicode strings from C++ methods that return std::string; the problem was showing up in afw's `testCameraGeom.py`.
> Fix `ConfigDict`'s handling of unicode keys

- python/lsst/pex/config/configChoiceField.py
- python/lsst/pex/config/configurableField.py
- python/lsst/pex/config/wrap.py
- tests/test_Config.py
- tests/test_configDictField.py
- tests/test_configurableField.py
- tests/test_dictField.py
- tests/test_listField.py
* `l` variable not allowed
* bare `except`.
> DM-12656: Deal with new flake8 warnings

- python/lsst/pex/config/choiceField.py
- python/lsst/pex/config/config.py
- python/lsst/pex/config/rangeField.py
This changes how the default Field constructor handles the `doc` argument.  It also changes how `ChoiceField` and `RangeField` handle `self.__doc__`.
Example base `Field`, `RangeField` and `ChoiceField`:
``` 
|  doWriteExposure
|      Write icExp and icExpBackground in addition to icSrc? Ignored if doWrite False. (`bool`)
|  
|  psfIterations
|      Number of iterations of detect sources, measure sources, estimate PSF. If useSimplePsf is True then 2 should be plenty; otherwise more may be wanted. (`int`)
|      
|      Valid Range = [1,inf)
|
|  flatScalingType
|      The method for scaling the flat on the fly. (`str`)
|      
|      Allowed values:
|      
|      USER
|        Scale by flatUserScale
|      MEAN
|        Scale by the inverse of the mean
|      MEDIAN
|        Scale by the …
```
> DM-13755: ReST-ify config doc strings

- python/lsst/pex/config/configurableField.py
Also fix a couple of minor other docstring problems, but not yet conforming to numpydoc standards.
> Add docstring to ConfigurableInstance.

- python/lsst/pex/config/configChoiceField.py
- python/lsst/pex/config/dictField.py
- python/lsst/pex/config/listField.py
- python/lsst/pex/config/registry.py
> DM-17088: Replace collections with collections.abc

- python/lsst/pex/config/config.py
The `Config.saveToStream` method has a new option to disable printing
all import statements. This is to support more human-friendly output for
`pipetask --show=config` option where import list is not useful but may
be overly long.
> DM-22301: Add option for printing configuration without imports

- tests/test_history.py
These lines appear to be incorrect for newer pytest versions.
> DM-24273: Remove tester-specific lines.

- .github/workflows/build.yaml
- python/lsst/pex/config/history.py
- python/lsst/pex/config/wrap.py
History of C++ defaults was recorded in the history list as a tuple
instead of StackFrame instance, I think this was a trivial omission. Also
fixed a crash in history formatting when history is empty.
> DM-27519: Fix couple of issues with history handling

- python/lsst/pex/config/config.py
In almost all cases a Field is operating on a config instance,
and there should be no need to check on every invocation of
__get__. Fallback to a check if normal operation does not
succeed.
> DM-32663 Assume Field is operating on Config instance

- python/lsst/pex/config/config.py
- tests/test_Config.py
The documentation and symmetry with `saveToStream` suggests that file-like objects were probably supposed to work, and probably did work once, but were broken at some point (and this wasn't noticed because all production calls apparently went through `load`).
To fix this while maintaining backwards compatibility, I added a `loadFromString` and moved much of the original implementation there (just shifted around the logic to guess the filename when it isn't provided), which lets both `loadFromStream` and load delegate to that without burdening either with type dispatch they don't need.
> DM-32733: Make loadFromStream actually accept file-like objects.

- python/lsst/pex/config/config.py
- python/lsst/pex/config/configChoiceField.py
- python/lsst/pex/config/configurableField.py
- python/lsst/pex/config/dictField.py
- python/lsst/pex/config/listField.py
- tests/test_configChoiceField.py
- tests/test_configurableField.py
- tests/test_dictField.py
- tests/test_listField.py
Pickling of these was already broken due to weakref usage, so this is about making the error message less cryptic.
> DM-33963: Directly disable pickling of proxy objects.

- python/lsst/pex/config/rangeField.py
I noticed this when adding a RangeField to meas_extensions_piff: the stated default for `inclusiveMax` in the docs didn't match the default value in the kwarg list, so I removed the redundant "(default)" lines.
> DM-34531: Fix incorrect RangeField docstrings

- python/lsst/pex/config/config.py
- tests/test_Config.py
The keys, items, and values methods now return python 3 compliant values.
> DM-7148: Remove the python 2 era iterkeys, iteritems, itervalues methods

- python/lsst/pex/config/config.py
- python/lsst/pex/config/configChoiceField.py
- python/lsst/pex/config/configDictField.py
- python/lsst/pex/config/configField.py
- python/lsst/pex/config/configurableField.py
- python/lsst/pex/config/dictField.py
- python/lsst/pex/config/listField.py
- setup.cfg
- tests/test_Config.py
- tests/test_dictField.py
- ups/pex_config.table
Add support for specifying the type of Fields with python class
typing syntax. This will ensure the appropriate type is inferred
from a Fields __get__ method, type checking when setting with
__set__, as well as setting appropriate dtypes where applicable at
runtime.
> DM-35312 Add support for python typing of Fields

- .github/workflows/build.yaml
- .pre-commit-config.yaml
- doc/lsst.pex.config/field-types.rst
- doc/lsst.pex.config/overview.rst
- doc/lsst.pex.config/wrapping-cpp-control-objects.rst
- doc/overview.dox
- pyproject.toml
- python/lsst/pex/config/config.py
- python/lsst/pex/config/configurableField.py
- python/lsst/pex/config/listField.py
> DM-37808: Update pre-commit dependencies

- .github/workflows/build.yaml
- doc/changes/DM-36649.feature.rst
- doc/lsst.pex.config/field-types.rst
- doc/lsst.pex.config/overview.rst
- pyproject.toml
- python/lsst/pex/config/configurableActions/__init__.py
- python/lsst/pex/config/configurableActions/_configurableAction.py
- python/lsst/pex/config/configurableActions/_configurableActionField.py
- python/lsst/pex/config/configurableActions/_configurableActionStructField.py
- python/lsst/pex/config/configurableActions/tests.py
- tests/test_configurableActions.py
> DM-36649: Move ConfigurableActions from pipe_tasks

- doc/changes/DM-31924.feature.md
- python/lsst/pex/config/registry.py
- tests/test_registry.py
> DM-31924: Add RegistryField machinery for dynamic defaults.

- doc/lsst.pex.config/field-types.rst
- doc/lsst.pex.config/overview.rst
- doc/lsst.pex.config/registry-intro.rst
Changed a few doc strings to be in sentence format/proper capitalization/punctation.
> DM-36696: Make pex.config example docs be consistently sentences

- doc/changes/DM-4037.misc.rst
- python/lsst/pex/config/config.py
- tests/test_Config.py
- tests/test_dictField.py
- tests/ticket2818helper/define.py
> DM-4037: Require non-empty doc string for config parameters

- .github/workflows/build.yaml
- COPYRIGHT
The above checklist is not applicable for this PR.
> DM-39747: Use correct Python versioning for PyPI

- doc/SConscript
This reverts commit e987fa42969f377e27b6b4227a1b2c8e95ab3000. The doxygen docs aren't needed for python, and do not render properly because of the change to numpydoc. We do still need docs for the C++ include file and removing doxygen completely breaks downstream documentation building where docs still assume they have access to pex_config doxygen configuration.
> Revert "Disable doxygen build with scons"

- doc/changes/DM-40198.api.md
- python/lsst/pex/config/config.py
- tests/test_Config.py
Allow a dictionary of variables to be used in local scope when configs are loaded from a stream or string.
> DM-40198 Allow extra local variables when loading configs

- .github/workflows/build.yaml
- .github/workflows/build_docs.yaml
- .github/workflows/docstyle.yaml
- .pre-commit-config.yaml
- doc/lsst.pex.config/CHANGES.rst
- pyproject.toml
- python/lsst/pex/config/config.py
- python/lsst/pex/config/configChoiceField.py
- python/lsst/pex/config/configField.py
- python/lsst/pex/config/configurableActions/_configurableActionField.py
- python/lsst/pex/config/configurableActions/_configurableActionStructField.py
- python/lsst/pex/config/configurableField.py
- python/lsst/pex/config/listField.py
- setup.cfg
> DM-44569: v27 release notes

- .pre-commit-config.yaml
- pyproject.toml
- python/lsst/pex/config/choiceField.py
- python/lsst/pex/config/comparison.py
- python/lsst/pex/config/config.py
- python/lsst/pex/config/configChoiceField.py
- python/lsst/pex/config/configDictField.py
- python/lsst/pex/config/configField.py
- python/lsst/pex/config/configurableActions/_configurableActionStructField.py
- python/lsst/pex/config/configurableField.py
- python/lsst/pex/config/dictField.py
- python/lsst/pex/config/history.py
- python/lsst/pex/config/listField.py
- python/lsst/pex/config/rangeField.py
- python/lsst/pex/config/registry.py
- python/lsst/pex/config/wrap.py
- tests/test_Config.py
- ups/pex_config.table
> DM-45209: Fix E721 error and general pyupgrade fixes

- doc/changes/DM-48074.feature.rst
- python/lsst/pex/config/configDictField.py
- python/lsst/pex/config/dictField.py
- python/lsst/pex/config/history.py
- python/lsst/pex/config/listField.py
- tests/test_configDictField.py
- tests/test_dictField.py
> DM-48074: Introduce keyCheck callback function for DictField and ConfigDictField

- python/lsst/pex/config/config.py
In numpy 2 numpy ints and floats stringify to np.int64/float64 and they can not be read back in again. This change forces numeric types to be converted to standard python types.
> DM-45545: Change autocast to handle numpy types

- doc/changes/DM-49121.feature.md
- python/lsst/pex/config/comparison.py
- python/lsst/pex/config/configDictField.py
- python/lsst/pex/config/configurableActions/_configurableActionStructField.py
- python/lsst/pex/config/dictField.py
- python/lsst/pex/config/listField.py
- tests/test_Config.py
The goal here is to let downstream code filter unimportant messages by looking at the prefix, which is now always the fully-qualified field name.
> DM-49121: Make config comparison output messages more consistent.

- doc/changes/DM-48074.feature.rst
- doc/changes/DM-49121.feature.md
- doc/lsst.pex.config/CHANGES.rst
> DM-49674 (v29): v29 release notes
